### ISSUE TITLE
Compare to other NIR types

### ISSUE THREAD

**Issue by kelle** [kelle/NIRTemplates_Manuscript#4]
> I am not sure it's enough for this paper to say that "optimal classification is important"
> and simply ignore all comparison between the types adopted here and all other
> other infrared classification work. The paper really needs to say something
> about an intercomparison of the area-infrared types adopted here, and those
> adopted in other systems.

**Comment by kelle** [comment]
email thread started with Adam Burgasser.

**Comment by kelle** [comment]
relevant text on line 162

**Comment by elliesch** [comment]
Analysis and plots completed. Plots can be found [here](https://github.com/elliesch/NIRSpecFigures/blob/master/plots.ipynb).
