### ISSUE TITLE
create Zenodo record for templates v1

### ISSUE THREAD

**Issue by kelle** [kelle/NIRTemplates_Manuscript#41]

**Comment by augustfly** [comment]
FWIW you may or may not want to wait for the MRT versions I'll send over later today. If you run into any issues with entering proper versioning in the Zenodo UI then pls let me know that too. Lastly, when this is published, it'd be great to add it to the AAS Community on Zenodo.

**Comment by kelle** [comment]
I should upload an archive of the .dat files and include bits of the Readme in the description? That seems to make sense to me.

**Comment by augustfly** [comment]
Yes, I think that is good. I'm always for more descriptive descriptions too. So go for it.

**Comment by kelle** [comment]
10.5281/zenodo.1064966

**Comment by augustfly** [comment]
Got it. So adding it to the main manuscript is the last step? You can ask yourself i you want to add it as an inline link or in the references/bibliography. It may be better as the latter.

**Comment by kelle** [comment]
https://zenodo.org/record/1064966#.WhXl27T80UE

**Comment by augustfly** [comment]
better: https://doi.org/10.5281/zenodo.1064966

**Comment by kelle** [comment]
I'll add it to the manuscript and .bib. (#45)
