### ISSUE TITLE
Review templates ReadMe and converted files

### ISSUE THREAD

**Issue by augustfly** [kelle/NIRTemplates_Manuscript#43]
Please review the attached ReadMe file and converted files for the templates. 

The ReadMe and converted files are packaged in a zip [suppmat3.zip](https://github.com/kelle/NIRTemplates_Manuscript/files/1496936/suppmat3.zip)

**Comment by kelle** [comment]
These look great! I think just remove the L5gammas from the Readme and its good to go.

**Comment by kelle** [comment]
Just thought of something : would be useful to add somewhere in the Readme that these templates are dubbed version 1. Can we add a link to the Zenodo record in the Readme as well?

**Comment by augustfly** [comment]
Yes, lets add the Zenodo DOI and version to the Readme.

**Comment by kelle** [comment]
Do you want me to add it or you got it. Here's the Zenodo DOI. I haven't published yet, but I have reserved the DOI. 10.5281/zenodo.1064966

**Comment by augustfly** [comment]
I will add it to the template ReadMe.
