### ISSUE TITLE
L5{gamma} templates

### ISSUE THREAD

**Issue by augustfly** [kelle/NIRTemplates_Manuscript#44]
There appear to be L5{gamma} template files but these are not in the Tables in the paper nor in Figure 9.

**Comment by kelle** [comment]
that's an oversight. Please remove
- L5J_g.txt
- L5H_g.txt
- L5_K_g.txt

I have updated the relevant repo. https://github.com/kelle/NIRSpecFigures/commit/e5da41aaadc60a3fb51c68f42fe1099f90b6a95c

**Comment by augustfly** [comment]
They are removed.
