### ISSUE TITLE
explain IQR

### ISSUE THREAD

**Issue by kelle** [kelle/NIRTemplates_Manuscript#6]
> o I am not familiar with the inter-quartile range (IQR) as a metric and its possible
> other readers also are not. This should be explained.
>

**Comment by alejocosmico** [comment]
I think the reviewer is just asking for an actual definition of the IQR. If that is the case, then we can change the wording in Section 4.1 where you first mention the IQR to something like: 

"The interquartile range (IQR), that is, the color range between the 25$^{th}$ and 75$^{th}$ percentiles, for the field gravity objects..."

If the reviewer is instead asking for the relevance/importance of the IQR, then it would probably be useful to cite some paper(s) making use of the IQR to illustrate their findings.
